<div class="row mb-2">
    <div class="col-md-6 offset-md-3 d-flex gap-2 flex-wrap">
    <a href="#" id="toggleBuildings" class="btn btn-secondary btn-sm">Gebäude an/aus</a>
    <a href="#" id="toggleResearches" class="btn btn-secondary btn-sm">Forschungen an/aus</a>
    <a href="#" id="toggleShips" class="btn btn-secondary btn-sm">Schiffe an/aus</a>
    <a href="#" id="toggleAdvisors" class="btn btn-secondary btn-sm">Berater an/aus</a>
    </div>
</div>
