<div class="row-fluid">
    <ul class="nav nav-tabs">
      <li><a href="<?= $this->url('galaxy', array('action'=>'index'));?>">Galaxy</a></li>
      <li class="active"><a href="#">System</a></li>
    </ul>
</div>

<?php
$scale  = $config['scale'];
$offset = $config['offset'];
$max = $scale * $config['range'];
$radius  = round($config['range']/2); ?>

<div id="system">
<div class="hidden">
    <div id="data_xMin"><?= $system['x'] - $radius;?></div>
    <div id="data_xMax"><?= $system['x'] + $radius;?></div>
    <div id="data_yMin"><?= $system['y'] - $radius;?></div>
    <div id="data_yMax"><?= $system['y'] + $radius;?></div>
    <div id="data_offset"><?= $offset?></div>
    <div id="data_range"><?= $config['range']?></div>
    <div id="data_scale"><?= $scale?></div>
</div>
<div class="row-fluid">
<div class="span3 well sidebar-nav">

    <ul class="nav nav-list fleetList">
      <li class="nav-header">Eigene Flotten</li>
        <?php
        $myFleets = $fleets;

        $foreignFleets = $myFleets;

        foreach ($myFleets as $fleet):
            $c = json_decode($fleet['coordinates'],true);
        ?>
            <li id="fid-<?= $fleet['id']?>">
                <a title="<?= "($c[0],$c[1],$c[2])"?>" href="#"><i class="icon-plane"></i> <?= $fleet['name'] ?></span>
            </li>
        <?php endforeach; ?>

      <li class="nav-header">Fremde Flotten</li>
      <?php foreach ($foreignFleets as $fleet):
        $c = json_decode($fleet['coordinates'],true);
      ?>
        <li id="fid-<?= $fleet['id']?>">
            <a title="<?= "($c[0],$c[1],$c[2])"?>" href="#"><i class="icon-plane"></i> <?= $fleet['name'] ?></span>
        </li>
      <?php endforeach; ?>
      <li class="nav-header">Planeten/Monde</li>
      <?php foreach ($objects as $o): ?>
      <li class=""><a href="#" title="(<?= $o['x'].','.$o['y'] ?>,0)"><i class="icon-globe"></i> <?= $o['name'] ?></a></li>
      <?php endforeach; ?>
    </ul>
</div><!--/span-->
<div class="span6">
<div id="parallax">
    <!-- <div id="systemBackground" class="parallax-layer" style="width:<?= $max+200 ?>px;height:<?= $max+200 ?>px;"></div><!-- background-image: url(/img/<?= $system['background_image_url'] ?>); -->
    <div id="systemLayer" class="parallax-layer" style="width:<?= $max+200 ?>px;height:<?= $max+200 ?>px;background-image: url(/img/grid.gif)">

<?php
    for ($x=$offset; $x <=$max+$offset; $x=$x+$scale):
        if ($x%50 == 0):
            echo '<p class="debug" style="left: '.$x.'px; top:'.$offset.'px; border: 1px dotted grey;">'.$x.'</p>';
        endif;
    endfor;
    for ($y=$offset; $y<=$max+$offset; $y=$y+$scale):
        if ($y%50 == 0):
            echo '<p class="debug" style="left: '.$offset.'px; top:'.$y.'px; border: 1px dotted grey;">'.$y.'</p>';
        endif;
    endfor;

    // planets and moons:
    foreach ($objects as $p):
        $m = $config['range'];
        $r = round($m/2);

        $left = round((($p['x'] + $r) % $m) * $scale) + $offset;
        $top  = round((($p['y'] + $r) % $m) * $scale) + $offset;

        $colony_count = 0
        ?>
            <div style="position:absolute;line-height:10px;top:<?= $top?>px;left:<?= $left?>px">
                <img id="pid-<?= $p['id']?>" src="/img/<?= $p['image_url'] ?>" width="<?= $scale ?>" height="<?= $scale ?>" />
                <ul id="pid-<?= $p['id']?>-spots" class="dropdown-menu spots" role="menu" aria-labelledby="dLabel">
                    <? foreach ($colonies as $cid => $colony):
                        if ($colony['system_object_id'] == $p['id']):
                            $colony_count += 1;
                    ?>
                    <li id="cid-<?= $cid ?>"><a tabindex="-1" href="#"><?= $colony['name'] ?></a></li>
                    <?  endif;
                    endforeach;
                    if ($colony_count == 0): ?>
                    <li><a tabindex="-1" href="#">keine Kolonien</a></li>
                    <? endif ?>
                </ul>
            </div>
        <? endforeach ?>
    </div>
</div>
</div>
<div class="span3 well">
  <h4>Infos</h4>
  <form name="fleetActions" action="#" method="POST">
    <input type="hidden" name="fleetId" value="" />
    <input type="text" name="coords"  value="" style="background-color: transparent; border: 0" />
    <?php foreach ($colonies as $i => $c):
    $x = (int) $c['x'];
    $y = (int) $c['y'];
    $z = (int) $c['spot'];
    ?>
    <ul id="cid-<?= $c['id']?>-info" class="unstyled colonyInfos">
        <li>Kolonie: <?= $c['name']?></li>
        <li>Größe: </li>
        <li>Spieler: </li>
        <li>Punkte: </li>
        <li>Allianz: </li>
        <li class="hidden coords"><?= json_encode(array($x,$y,$z)) ?></li>
    </ul>
    <?php endforeach;?>

    <div id="fleetActions">
        <button type="submit" class="btn btn-large btn-block" name="order" value="move" >Bewegen</button>
        <button type="submit" class="btn btn-large btn-block" name="order" value="transport" >Transport</button>
        <button type="submit" class="btn btn-large btn-block" name="order" value="attack" >Angriff</button>
        <div class="error" style="display:none"></div>
    </div>
  </form>
</div>
</div><!--/row-->