before_commands:
    - 'composer install --no-progress'
filter:
    excluded_paths:
        - vendor/
        - bin/
        - config/
        - templates/
        - cli/
tools:
    php_mess_detector: true
    php_analyzer: true
    php_code_sniffer: true
    php_cpd: true
    php_loc: true
    php_pdepend: true
