<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'INNN\Module'                              => __DIR__ . '/Module.php',
    'INNN\Controller\ArchiveController'        => __DIR__ . '/src/INNN/Controller/ArchiveController.php',
    'INNN\Controller\ArchiveControllerFactory' => __DIR__ . '/src/INNN/Controller/ArchiveControllerFactory.php',
    'INNN\Controller\EventController'          => __DIR__ . '/src/INNN/Controller/EventController.php',
    'INNN\Controller\EventControllerFactory'   => __DIR__ . '/src/INNN/Controller/EventControllerFactory.php',
    'INNN\Controller\JsonController'           => __DIR__ . '/src/INNN/Controller/JsonController.php',
    'INNN\Controller\JsonControllerFactory'    => __DIR__ . '/src/INNN/Controller/JsonControllerFactory.php',
    'INNN\Controller\MessageController'        => __DIR__ . '/src/INNN/Controller/MessageController.php',
    'INNN\Controller\MessageControllerFactory' => __DIR__ . '/src/INNN/Controller/MessageControllerFactory.php',
    'INNN\Entity\Event'                        => __DIR__ . '/src/INNN/Entity/Event.php',
    'INNN\Entity\EventFactory'                 => __DIR__ . '/src/INNN/Entity/EventFactory.php',
    'INNN\Entity\Message'                      => __DIR__ . '/src/INNN/Entity/Message.php',
    'INNN\Entity\MessageFactory'               => __DIR__ . '/src/INNN/Entity/MessageFactory.php',
    'INNN\Service\Event'                       => __DIR__ . '/src/INNN/Service/Event.php',
    'INNN\Service\EventFactory'                => __DIR__ . '/src/INNN/Service/EventFactory.php',
    'INNN\Service\Message'                     => __DIR__ . '/src/INNN/Service/Message.php',
    'INNN\Service\MessageFactory'              => __DIR__ . '/src/INNN/Service/MessageFactory.php',
    'INNN\Table\Event'                         => __DIR__ . '/src/INNN/Table/Event.php',
    'INNN\Table\Message'                       => __DIR__ . '/src/INNN/Table/Message.php',
);