<?php
$resources = $resources->toArray();
foreach ($costs as $cost):
    $resource = $resources[ $cost->resource_id ];
    $resouce = $resource['name'];
    $abbreviation =  $resource['abbreviation'];
    $class =  $resource['icon'];
    $amount  = $cost['amount'];
    echo '<a data-placement="bottom" rel="tooltip" href="#" data-original-title="'.$resource.'">';
    echo '<i class="'.$class.'">'.$abbreviation.'</i>'.$amount.'</a>';
endforeach;
?>