<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Core\Module'                          => __DIR__ . '/Module.php',
  'CoreTest\Service\AbstractServiceTest' => __DIR__ . '/test/CoreTest/Service/AbstractServiceTest.php',
  'CoreTest\Table\AbstractTableTest'     => __DIR__ . '/test/CoreTest/Table/AbstractTableTest.php',
  'CoreTest\AbstractBootstrap'           => __DIR__ . '/test/AbstractBootstrap.php',
  'Core\Service\Exception'               => __DIR__ . '/src/Core/Service/Exception.php',
  'Core\Service\AbstractService'         => __DIR__ . '/src/Core/Service/AbstractService.php',
  'Core\Service\Tick'                    => __DIR__ . '/src/Core/Service/Tick.php',
  'Core\Model\ResultSet'                 => __DIR__ . '/src/Core/Model/ResultSet.php',
  'Core\Model\Exception'                 => __DIR__ . '/src/Core/Model/Exception.php',
  'Core\Table\Exception'                 => __DIR__ . '/src/Core/Table/Exception.php',
  'Core\Table\AbstractTable'             => __DIR__ . '/src/Core/Table/AbstractTable.php',
  'Core\Exception\Exception'             => __DIR__ . '/src/Core/Entity/Exception.php',
  'Core\Entity\EntityInterface'          => __DIR__ . '/src/Core/Entity/EntityInterface.php',
  'Core\Entity\AbstractEntity'           => __DIR__ . '/src/Core/Entity/AbstractEntity.php',
  'Core\Controller\IngameController'     => __DIR__ . '/src/Core/Controller/IngameController.php',
);
