<div class="row-fluid"  id="colony">

    <? # $this->technologyNameLink(25,0)?>

  <div id="visualTechtree" class="carousel slide row-fluid">
    <!-- Carousel items -->
    <div class="carousel-inner">
      <?php for ($stage=0; $stage<=5; $stage++): ?>
      <div class="stage <?= ($stage==0) ? 'active' : '' ?> item" id="stage-<?= $stage ?>">
        <svg class="span12 stage-svg" id="stage-<?= $stage ?>-svg" height="100%" width="100%" style="position:absolute">
        <!-- <rect x="0" y="0" height="10" width="10" stroke="black" /> -->
        <!-- svg content via javascript -->
        </svg>

        <div class="span12 stage-grid" style="position:absolute">
        <?php for ($row=0; $row<10; $row++): ?>
          <div class="row-fluid">
              <?php for ($col=0; $col<=5; $col++): ?>
              <span class="span2" id="<?= "tech-$stage-$row-$col"?>"></span>
              <?php endfor; ?>
          </div>
        <?php endfor; ?>
        </div>
      </div>
      <?php endfor; ?>

    <div class="hidden">
        <?php foreach ($techtree as $id => $tech) :
        /* attention: x and y data is stored for the vertical techtree but used
         * for a horizontal techtree view, so a grid row is represented by the X
         * value instead of the Y Value (TODO: this should be fixed in future) */
        $grid_x = $tech['graph_row'];
        $grid_y = $tech['graph_column'];
        $key = $tech['stage'] . '-' . $grid_x . '-' . $grid_y;
        ?>
        <span class="techdata" id="techsource-<?= $key ?>">
            <a id="tech-<?= $id ?>" class="btn btn-block <?= $tech['type'] ?>" href="#techModal" data-toggle="modal">
                <? if (!empty($tech['order'])):
                    echo '<i class="icon-arrow-up"></i>';
                endif;
                echo $this->translate($tech['name'], null, 'de_DE') . ' ' . $tech['count']  ?>
            </a>
            <span class="hidden data"><?= json_encode($tech) ?></span>
        </span>
        <?php endforeach;

        foreach ($requirements as $id => $req):
            foreach ($req as $toId => $val):
                $key = $id . '-' . $toId;
                /*$fullfilled = ($techtree[$id]['count'] >= $val['required_tech_count']) ? 'true' : 'false';*/
                $tech_count = $techtree[$id]['count'];
                $required_tech_count = $val['required_tech_count'];
        ?>

        <div class="requirementsdata" id="requirementsource-<?= $key ?>"><?= sprintf("%s-%s-%s-%s", $id, $toId, $required_tech_count, $tech_count) ?></div>

        <?php endforeach;
        endforeach; ?>
    </div>


    <!-- Carousel nav -->
    <a class="carousel-control left" href="#visualTechtree" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#visualTechtree" data-slide="next">&rsaquo;</a>
  </div>

  <!-- Modal -->
  <!-- this Modal is filled with html data from json request -->
  <div id="techModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Loading...</h3>
      </div>
      <div class="modal-body">
          <p>Loading...</p>
          <hr />
      </div>
      <div class="modal-footer">

      </div>
    </div>
</div>