<div class="row-fluid"  id="colony">

    <? # $this->technologyNameLink(25,0)?>

  <div id="visualTechtree" class="carousel slide row-fluid">
    <!-- Carousel items -->
    <div class="carousel-inner">
      <?php for ($stage=0; $stage<=5; $stage++): ?>
      <div class="<?= ($stage==0) ? 'active' : '' ?> item" id="stage-<?= $stage ?>">
        <svg class="span12" id="stage-<?= $stage ?>-svg" height="100%" width="100%" style="position:absolute">
            <rect x="0" y="0" height="10" width="10" stroke="black" />
        <!-- svg content via javascript -->
        </svg>

        <div class="span12" style="position:absolute">
        <?php for ($row=0; $row<10; $row++): ?>
          <div class="row-fluid">
              <?php for ($col=0; $col<=5; $col++): ?>
              <span class="span2" id="<?= "tech-$stage-$row-$col"?>"></span>
              <?php endfor; ?>
          </div>
        <?php endfor; ?>
        </div>
      </div>
      <?php endfor; ?>

    <div class="hidden">
        <?php foreach ($techtree as $id => $tech) :
        $key = $tech['stage'] . '-' . $tech['graph_row'] . '-' . $tech['graph_column'];
        ?>
        <span class="techdata" id="techsource-<?= $key ?>">
            <a id="tech-<?= $id ?>" class="btn btn-block" href="#techModal" data-toggle="modal"><?= $this->translate($tech['name']) . '<br />' . $tech['count'] ?> // <?= $key ?></a>
        </span>
        <?php endforeach;

        foreach ($requirements as $id => $req):
            $from = $techtree[$id]['stage'] . '-' . $techtree[$id]['graph_row'] . '-' . $techtree[$id]['graph_column'];
            foreach ($req as $toId => $val):
                $key = $id . '-' . $toId;
                $to = $techtree[$id]['stage'] . '-' . $techtree[$id]['graph_row'] . '-' . $techtree[$id]['graph_column'];
        ?>

        <div class="requirementsdata" id="requirementsource-<?= $key ?>"><?= sprintf("%s-%s-%s", $id, $toId, $val['required_tech_count']) ?></div>

        <?php endforeach;
        endforeach; ?>
    </div>


    <!-- Carousel nav -->
    <a class="carousel-control left" href="#visualTechtree" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#visualTechtree" data-slide="next">&rsaquo;</a>
  </div>

  <!-- Modal -->
  <div id="techModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Modal header</h3>
      </div>
      <div class="modal-body">
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <hr />
          <div class="span3">
            <a class="btn btn-block" href="#"><i class="icon-plus"></i>Ausbauen</a>
            <a class="btn btn-block" href="#"><i class="icon-minus"></i>Zurückbauen</a>
            <a class="btn btn-block" href="#"><i class="icon-wrench"></i>Reparieren</a>
          </div>
          <div class="span2">
            <?= $this->partial('layout/resource-bar', array()); ?>
          </div>
      </div>
      <div class="modal-footer">
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-plus"></i> Ausbauen</button>
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-minus"></i> Zurückbauen</button>
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-wrench"></i> Reparieren</button>
        <button class="btn" data-dismiss="modal" aria-hidden="true"><i class="icon-remove"></i> Close</button>
        <!--<button class="btn btn-primary">Save changes</button>-->
      </div>
    </div>
</div>