<?= $this->partial('partial/_switch_tech_display') ?>
<hr />
<div class="row-fluid"  id="colony">
  <div id="visualTechtree" class="row-fluid" style="position:relative">
      <div id="storage-tech-id" class="hidden"></div>
      <div id="storage" class="hidden"></div>
    <svg class="grid-svg" id="grid-svg" height="100%" width="100%" >
        <rect x="0" y="0" height="10" width="10" stroke="black" />
        <rect x="100" y="100" height="10" width="10" stroke="black" />
        <!-- svg content via javascript -->
    </svg>

    <div class="grid">
    <?php for ($row=0; $row<=15; $row++): ?>
      <div class="row-fluid">
          <?php for ($col=0; $col<=5; $col++): ?>
          <span class="span2 grid-cell" id="<?= "grid-$row-$col"?>"></span>
          <?php endfor; ?>
      </div>
    <?php endfor; ?>
    </div>

    <div class="hidden">
        <?php
        foreach ($techtree as $id => $tech) :
            echo $this->partial("partial/_techdata", array('tech'=>$tech));
        endforeach;

        foreach ($requirements as $toId => $req):
            foreach ($req as $fromId => $val):
                echo $this->partial("partial/_techrequirement", array(
                        'fromTech'=>$techtree[$fromId],
                        'toTech'=>$techtree[$toId],
                        'required_tech_count'=>$val['required_tech_count']
                ));
            endforeach;
        endforeach; ?>
  </div>

  <!-- Modal -->
  <!-- this Modal is filled with html data from json request -->
  <div id="techModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3 id="myModalLabel">Loading...</h3>
      </div>
      <div class="modal-body">
          <p>Loading...</p>
          <hr />
      </div>
      <div class="modal-footer">

      </div>
    </div>
</div>