<?php
$form = $this->loginForm;
$form->prepare();
$form->setAttribute('action', $this->url('zfcuser/login'));
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'navbar-search pull-right form-horizontal');
$elementDisplayOptions = array();
#$formType = \DluTwBootstrap\Form\FormUtil::FORM_TYPE_INLINE;
$formType = null;
echo $this->formTwb()->openTag($form, $formType)."\n"; ?>
    <?= $this->formElementErrors($form->get('identity')) ?>
    <?= $this->formInputTwb($form->get('identity'), $formType, array('class'=>'span2', 'placeholder' => 'Login')) ?>
    <?= $this->formInputTwb($form->get('credential'), $formType, array('class'=>'span2', 'placeholder' => 'Password')) ?>
<?php if ($this->redirect): ?>
    <input type="hidden" name="redirect" value="<?php echo $this->redirect ?>" />
<?php endif; ?>
    <?= $this->formButton($form->get('submit', $formType)); ?>
<?= $this->form()->closeTag(); ?>
<? if ($this->enableRegistration) : ?>
Not registered? <a href="<?php echo $this->url('zfcuser/register') . ($this->redirect ? '?redirect='.$this->redirect : '') ?>">Sign up!</a>
<?php endif; ?>
