<div class="row-fluid">
    <ul class="nav nav-tabs">
        <li><a href="<?= $this->url('innn/new') ?>">New Message</a></li>
        <li class="active"><a href="<?= $this->url('innn/inbox') ?>">Inbox</a></li>
        <li><a href="<?= $this->url('innn/outbox') ?>">Outbox</a></li>
        <li class="secondary-nav"><a href="<?= $this->url('innn/archive') ?>">Archive</a></li>
    </ul>
</div>
<div class="row-fluid">

</div><!--/row-->
