<?php if ($this->success): ?>
<div class="alert alert-success">Flotte wurde erstellt!</div>
<?php endif; ?>

<div id="fleetconfig">
    <?php if (!empty($fleet)): ?>
    <div class="hidden" id="fleet_id"><?php echo $fleet->getId() ?></div>
    <?php endif; ?>
    <?php if (!empty($colony)): ?>
    <div class="hidden" id="colony_id"><?php echo $colony->getId() ?></div>
    <?php endif; ?>
<?php if ($fleetIsInColonyOrbit): ?>
    <div class="row">
        <div class="col-md-5" style="text-align: right"><h3><small>Schiffe auf</small> <?php echo $this->translate('colony') ?></h3></div>
        <div class="col-md-2"></div>
        <div class="col-md-5"><h3><small>Schiffe in</small> <?php echo $this->translate('fleet') ?></h3></div>
    </div>
    <?php echo $this->partial('fleet/partial/_fleet_entity_rows', array('techs' => $ships, 'type' => 'ship')); ?>

    <div class="row">
        <div class="col-md-5" style="text-align: right"><h3><small>Personal auf</small> <?php echo $this->translate('colony') ?></h3></div>
        <div class="col-md-2"></div>
        <div class="col-md-5"><h3><small>Personal als</small> <?php echo $this->translate('crew') ?></h3></div>
    </div>
    <?php echo $this->partial('fleet/partial/_fleet_entity_rows', array('techs' => $personells, 'type' => 'personell')); ?>

    <div class="row">
        <div class="col-md-5" style="text-align: right"><h3><small>Personal auf</small> <?php echo $this->translate('colony') ?></h3></div>
        <div class="col-md-2"></div>
        <div class="col-md-5"><h3><small>Personal als</small> <?php echo $this->translate('passenger') ?></h3></div>
    </div>
    <?php echo $this->partial('fleet/partial/_fleet_entity_cargo_rows', array('techs' => $personells, 'type' => 'personell')); ?>

    <div class="row">
        <div class="col-md-5" style="text-align: right"><h3><small>Forschungen auf</small> <?php echo $this->translate('colony') ?></h3></div>
        <div class="col-md-2"></div>
        <div class="col-md-5"><h3><small>Forschungen in</small> <?php echo $this->translate('fleet_cargo') ?></h3></div>
    </div>
    <?php echo $this->partial('fleet/partial/_fleet_entity_cargo_rows', array('techs' => $researches, 'type' => 'research')); ?>

    <div class="row">
        <div class="col-md-5" style="text-align: right"><h3><small>Ressourcen auf</small> <?php echo $this->translate('colony') ?></h3></div>
        <div class="col-md-2"></div>
        <div class="col-md-5"><h3><small>Ressourcen in</small> <?php echo $this->translate('fleet_cargo') ?></h3></div>
    </div>
<?php  foreach ($resources as $resId => $resource):
        if ($resource["is_tradeable"] == 1):
?>
    <div class="row item resource" id="resource-<?php echo $resId ?>">
        <div class="col-md-4 transferButtons" style="text-align: right">
            <button class="btn btn-default cargo" value="-100">100</button>
            <button class="btn btn-default cargo" value="-50">50</button>
            <button class="btn btn-default cargo" value="-10">10</button>
        </div>
        <div class="col-md-1 countOnColony resourceOnColony-<?php echo $resId ?>" style="text-align: center">0</div>
        <div class="col-md-2" style="text-align: center"><?php echo $this->translate($resource["name"]) ?></div>
        <div class="col-md-1 countInFleetCargo resourceInFleetCargo-<?php echo $resId ?>" style="text-align: center">0</div>
        <div class="col-md-4 transferButtons">
            <button class="btn btn-default cargo" value="10">10</button>
            <button class="btn btn-default cargo" value="50">50</button>
            <button class="btn btn-default cargo" value="100">100</button>
        </div>
    </div>
<?php      endif;
    endforeach;
endif; ?>
</div>
