<div id="fleetlist">
    <?php if ($cid): ?>
        <p style="text-align: center">Flotten auf der Kolonie und in der näheren Umgebung.</p>
    <?php elseif($pid): ?>
        <p style="text-align: center">Flotten auf dem Planeten und in der näheren Umgebung.</p>
    <?php elseif($sid): ?>
        <p style="text-align: center">Flotten im System.</p>
    <?php endif; ?>
    <div class="row">
        <div class="col-md-6 well">
            <h4>eigene Flotten</h4>
            <table class="table table-striped">
                <tr>
                    <th>Flotte</th>
                    <th>Position</th>
                    <th>Aktion</th>
                    <th></th>
                </tr>
            <?php
            foreach ($fleets as $fleet):
            if ($fleet['user_id'] == $userId): ?>
            <tr class="">
                <td><a href="<?php echo $this->url('fleet/config', array('id' => $fleet['id'])) ?>"><i class="glyphicon glyphicon-search"></i><?php echo $fleet['fleet'] ?></a></td>
                <?php
                if (isset($colony) && $colony['x'] == $fleet['x'] && $colony['y'] == $fleet['y'] ): ?>
                <td>angedockt</td>
                <td><?php
                if (isset($myFleetOrders[$fleet['id']])):
                    $myOrders = $myFleetOrders[$fleet['id']]['order'];
                    echo $myFleetOrders[$fleet['id']]['order'];
                else:
                    echo 'leer';
                endif; ?></td>
                <td>
                    <?php echo ($trade) ? '<a class="button" href="#">Auftrag zuweisen</a>' : 'befehligen' ?>
                </td>
                <td><a class="btn btn-default" href="/fleet/delete/<?php echo $fleet['id']?>"><i class="glyphicon glyphicon-remove"></i></a></td>
                <?php else:?>
                <td><?php echo $fleet['x'] . ','. $fleet['y'] . ',' . $fleet['spot'] ?></td>
                <td></td>
                <td><a class="btn btn-default disabled"><i class="glyphicon glyphicon-remove"></i></a></td>
                <?php endif;?>
            </tr>
            <?php endif;
            endforeach;?>
            <tr>
                <td colspan="3">
                <form action="<?php echo $this->url('fleet', array('action' => 'create'));?>" method="post" id="createFleetForm">
                    <input type="hidden" id="coords" name="coords" value="<?php echo "[$x, $y, 0]" ?>" />
                    <input type="text" id="fleet" name="fleet" />
                    <input class="btn btn-default" type="submit" value="Erstellen" id="submit" name="submit" />
                </form>
                </td>
            </tr>
            </table>
        </div>
        <?php #if ($cid || $pid || $sid): ?>
        <div class="col-md-6 well">
            <h4>fremde Flotten</h4>
            <table class="table table-striped">
                <tr>
                    <th>Flotte</th>
                    <th>Position</th>
                    <th>Aktion</th>
                    <th></th>
                    <th></th>
                </tr>
            <?php foreach ($fleets as $fleet):
                if ( $fleet['user_id'] != $userId): ?>
                <tr>
                    <td><?php echo $fleet['fleet'] ?></td>
                    <td><?php echo $fleet['x'] . ','. $fleet['y'] . ',' . $fleet['spot'] ?></td>
                    <td></td>
                </tr>
                <?php endif;
            endforeach; ?>
            </table>
        </div>
        <?php #endif; ?>
    </div>
</div>
