<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Nouron\Module'                => __DIR__ . '/Module.php',
    'Nouron\Model\AbstractTable'   => __DIR__ . '/src/Nouron/Model/AbstractTable.php',
    'Nouron\Model\EntityDummy'     => __DIR__ . '/src/Nouron/Model/EntityDummy.php',
    'Nouron\Model\EntityInterface' => __DIR__ . '/src/Nouron/Model/EntityInterface.php',
    'Nouron\Model\ResultSet'       => __DIR__ . '/src/Nouron/Model/ResultSet.php',
    'Nouron\Service\Exception'     => __DIR__ . '/src/Nouron/Service/Exception.php',
    'Nouron\Service\Gateway'       => __DIR__ . '/src/Nouron/Service/Gateway.php',
    'Nouron\Service\Tick'          => __DIR__ . '/src/Nouron/Service/Tick.php',
);