<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Nouron\Module'                      => __DIR__ . '/Module.php',
    'Nouron\Controller\IngameController' => __DIR__ . '/src/Nouron/Controller/IngameController.php',
    'Nouron\Entity\AbstractEntity'       => __DIR__ . '/src/Nouron/Entity/AbstractEntity.php',
    'Nouron\Entity\EntityInterface'      => __DIR__ . '/src/Nouron/Entity/EntityInterface.php',
    'Nouron\Model\Exception'             => __DIR__ . '/src/Nouron/Model/Exception.php',
    'Nouron\Model\ResultSet'             => __DIR__ . '/src/Nouron/Model/ResultSet.php',
    'Nouron\Service\AbstractService'     => __DIR__ . '/src/Nouron/Service/AbstractService.php',
    'Nouron\Service\Exception'           => __DIR__ . '/src/Nouron/Service/Exception.php',
    'Nouron\Service\Tick'                => __DIR__ . '/src/Nouron/Service/Tick.php',
    'Nouron\Table\AbstractTable'         => __DIR__ . '/src/Nouron/Table/AbstractTable.php',
    'NouronTest\Service\AbstractServiceTest' => __DIR__ . '/test/NouronTest/Service/AbstractServiceTest.php'
);
