<div class="row mb-2" id="trade">
    <div class="col-md-10">
    <?php echo $this->form($searchForm->prepare()); ?>
    </div>
    <div class="col-md-2">
        <a id="newOfferButton" class="btn btn-secondary" href="#newTradeOfferModal" data-bs-toggle="modal"><i class="bi bi-plus"></i> Angebot erstellen</a>
    </div>
</div>
<div class="row">
    <div class="col-12">
    <?php echo $this->paginationControl($paginator, null, null, array('route' => 'trade')); ?>
    <table class="table">
    <tr>
        <th><?php echo $this->translate('colony') ?></th>
        <th><?php echo $this->translate('offer-type') ?></th>
        <th><?php echo $this->translate('resource') ?></th>
        <th><?php echo $this->translate('amount') ?></th>
        <th><?php echo $this->translate('price per unit') ?></th>
        <th><?php echo $this->translate('restriction') ?></th>
        <th></th>
    </tr>
    <?php foreach ($paginator as $offer): ?>
        <tr id="offer-resource-<?php echo $offer['colony_id'] ?>-<?php echo $offer['resource_id'] ?>">
            <?php if ($offer['user_id'] != $user_id): ?>
            <td><?php echo $offer['colony']?> (<a href=""><i class="bi bi-envelope"></i> <?php echo $offer['username']?></a>)</td>
            <?php else: ?>
            <td><?php echo $offer['colony']?></td>
            <?php endif ?>
            <td><?php echo ($offer['direction']) ? 'Verkauf' : 'Kauf' ?></td>
            <td><?php $resName = $this->translate($resources[$offer['resource_id']]['name']) ?>
            <a data-bs-placement="bottom" data-bs-toggle="tooltip" href="#" title="<?php echo $resName ?>"><i class="<?php echo $resources[$offer['resource_id']]['icon'] ?>"></i> <?php echo $resName ?></a>
            </td>
            <td><?php echo $offer['amount'] ?></td>
            <td><?php echo $offer['price'] ?></td>
            <td><?php echo $offer['restriction'] ?></td>
            <?php if ($offer['user_id'] == $user_id): ?>
            <td><a href="/trade/remove-offer" class="btn btn-sm btn-secondary removeOfferButton" title="Angebot entfernen"><i class="bi bi-x-lg"></i></a></td>
            <?php else: ?>
            <td></td>
            <?php endif; ?>
        </tr>
    <?php endforeach; ?>
    </table>

    <?php echo $this->paginationControl($paginator, null, null, array('route' => 'trade')); ?>
</div>

<!-- Modal -->
<div id="newTradeOfferModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="newTradeOfferModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title" id="newTradeOfferModalLabel"><?php echo $this->translate("new-offer") ?></h3>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Schließen"></button>
        </div>
        <div class="modal-body">
            <?php echo $this->form($newOfferForm->prepare()); ?>
        </div>
    </div>
  </div>
</div>
