<div class="row-fluid" id="trade">
    <div class="span10">
    <?= $this->formTwb($searchForm->prepare(), 'inline'); ?>
    </div>
    <div class="span2">
        <a id="newOfferButton" class="btn" href="#newTradeOfferModal" data-toggle="modal"><i class="icon-plus"></i> Angebot erstellen</a>
    </div>
    <table class="table">
    <tr>
        <th><?= $this->translate('colony') ?></th>
        <th><?= $this->translate('offer-type') ?></th>
        <th><?= $this->translate('resource') ?></th>
        <th><?= $this->translate('amount') ?></th>
        <th><?= $this->translate('credits-per-unit') ?></th>
        <th><?= $this->translate('restriction') ?></th>
    </tr>
    <?php foreach ($paginator as $offer): ?>
        <tr id="offer-<?= $offer['id']?>">
            <td><?= $offer['colony_id']?></td>
            <td><?= ($offer['direction']) ? 'Verkauf' : 'Kauf' ?></td>
            <td><?php $resName = $this->translate($resources[$offer['resource_id']]['name']) ?>
            <a data-placement="bottom" rel="tooltip" href="#" data-original-title="<?= $resName ?>"><i class="<?= $resources[$offer['resource_id']]['icon'] ?>"></i> <?= $resName ?></a>
            </td>
            <td><?= $offer['amount']?></td>
            <td><?= $offer['price']?></td>
            <td><?= $offer['restriction']?></td>
        </tr>
    <?php endforeach; ?>
    </table>

    <?= $this->paginationControl($paginator, null, null, array('route' => 'trade')); ?>
</div>

<!-- Modal -->
<!-- this Modal is filled with html data from json request -->
<div id="newTradeOfferModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="newTradeOfferModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="newTradeOfferModalLabel"><?= $this->translate("new-offer") ?></h3>
    </div>
    <div class="modal-body">
        <?= $this->formTwb($newOfferForm->prepare()); ?>
    </div>
    <!-- <div class="modal-footer">

    </div> -->
</div>