<div class="row-fluid" id="trade">
    <?
    $form = $this->searchForm;
    $form->prepare();
    echo $this->formTwb($form, 'inline');
    ?>

    <?= $this->paginationControl($paginator, null, null, array('route' => 'trade')); ?>

    <table class="table">
    <tr>
        <th><?= $this->translate('colony') ?></th>
        <th><?= $this->translate('offer-type') ?></th>
        <th><?= $this->translate('technology') ?></th>
        <th><?= $this->translate('count') ?></th>
        <th><?= $this->translate('credits-per-unit') ?></th>
        <th><?= $this->translate('restriction') ?></th>
    </tr>
    <?php foreach ($paginator as $offer): ?>
        <tr id="offer-<?= $offer['id']?>">
            <td><?= $offer['colony_id']?></td>
            <td><?= ($offer['direction']) ? 'Verkauf' : 'Kauf' ?></td>
            <td><?= $offer['tech_id']?></td>
            <td><?= $offer['amount']?></td>
            <td><?= $offer['price']?></td>
            <td><?= $offer['restriction']?></td>
        </tr>
    <?php endforeach; ?>
    </table>


    <?= $this->paginationControl($paginator, null, null, array('route' => 'trade')); ?>

</div>