<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'User\Module'                               => __DIR__ . '/Module.php',
  'User\Service\UserServiceFactory'           => __DIR__ . '/src/User/Service/UserServiceFactory.php',
  'User\Service\UserService'                  => __DIR__ . '/src/User/Service/UserService.php',
  'User\Table\UserTable'                      => __DIR__ . '/src/User/Table/UserTable.php',
  'User\Table\UserTableFactory'               => __DIR__ . '/src/User/Table/UserTableFactory.php',
  'User\Entity\UserFactory'                   => __DIR__ . '/src/User/Entity/UserFactory.php',
  'User\Entity\User'                          => __DIR__ . '/src/User/Entity/User.php',
  'User\Controller\SettingsController'        => __DIR__ . '/src/User/Controller/SettingsController.php',
  'User\Controller\ContactsController'        => __DIR__ . '/src/User/Controller/ContactsController.php',
  'User\Controller\SettingsControllerFactory' => __DIR__ . '/src/User/Controller/SettingsControllerFactory.php',
  'User\Controller\UserControllerFactory'     => __DIR__ . '/src/User/Controller/UserControllerFactory.php',
  'User\Controller\UserController'            => __DIR__ . '/src/User/Controller/UserController.php',
  'User\View\Helper\UserNameLink'             => __DIR__ . '/src/User/View/Helper/UserNameLink.php',
);
