<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'User\Module'                               => __DIR__ . '/Module.php',
    'User\Controller\ContactsController'        => __DIR__ . '/src/User/Controller/ContactsController.php',
    'User\Controller\SettingsController'        => __DIR__ . '/src/User/Controller/SettingsController.php',
    'User\Controller\SettingsControllerFactory' => __DIR__ . '/src/User/Controller/SettingsControllerFactory.php',
    'User\Entity\User'                          => __DIR__ . '/src/User/Entity/User.php',
);