<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Application\Module'                        => __DIR__ . '/Module.php',
    'Application\Cache\CacheFactory'            => __DIR__ . '/src/Application/Cache/CacheFactory.php',
    'Application\Controller\IndexController'    => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Controller\LoggerAware'        => __DIR__ . '/src/Application/Controller/LoggerAware.php',
    'Application\Controller\Plugin\GetActive'   => __DIR__ . '/src/Application/Controller/Plugin/GetActive.php',
    'Application\Controller\Plugin\GetSelected' => __DIR__ . '/src/Application/Controller/Plugin/GetSelected.php',
);
