<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Galaxy\Module'                            => __DIR__ . '/Module.php',
    'Galaxy\Controller\IndexController'        => __DIR__ . '/src/Galaxy/Controller/IndexController.php',
    'Galaxy\Controller\IndexControllerFactory' => __DIR__ . '/src/Galaxy/Controller/IndexControllerFactory.php',
    'Galaxy\Mapper\Colony'                     => __DIR__ . '/src/Galaxy/Mapper/Colony.php',
    'Galaxy\Mapper\ColonyFactory'              => __DIR__ . '/src/Galaxy/Mapper/ColonyFactory.php',
    'Galaxy\Model\Colony'                      => __DIR__ . '/src/Galaxy/Model/Colony.php',
    'Galaxy\Model\ColonyTable'                 => __DIR__ . '/src/Galaxy/Model/ColonyTable.php',
    'Galaxy\Model\System'                      => __DIR__ . '/src/Galaxy/Model/System.php',
    'Galaxy\Model\SystemTable'                 => __DIR__ . '/src/Galaxy/Model/SystemTable.php',
    'Galaxy\Service\Gateway'                   => __DIR__ . '/src/Galaxy/Service/Gateway.php',
    'Galaxy\Service\GatewayFactory'            => __DIR__ . '/src/Galaxy/Service/GatewayFactory.php',
    'Galaxy\Table\Colony'                      => __DIR__ . '/src/Galaxy/Table/Colony.php',
);