<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Galaxy\Module'                             => __DIR__ . '/Module.php',
    'Galaxy\Controller\IndexController'         => __DIR__ . '/src/Galaxy/Controller/IndexController.php',
    'Galaxy\Controller\IndexControllerFactory'  => __DIR__ . '/src/Galaxy/Controller/IndexControllerFactory.php',
    'Galaxy\Controller\Plugin\SelectedIds'      => __DIR__ . '/src/Galaxy/Controller/Plugin/SelectedIds.php',
    'Galaxy\Controller\SystemController'        => __DIR__ . '/src/Galaxy/Controller/SystemController.php',
    'Galaxy\Controller\SystemControllerFactory' => __DIR__ . '/src/Galaxy/Controller/SystemControllerFactory.php',
    'Galaxy\Mapper\Colony'                      => __DIR__ . '/src/Galaxy/Mapper/Colony.php',
    'Galaxy\Mapper\ColonyFactory'               => __DIR__ . '/src/Galaxy/Mapper/ColonyFactory.php',
    'Galaxy\Mapper\System'                      => __DIR__ . '/src/Galaxy/Mapper/System.php',
    'Galaxy\Mapper\SystemFactory'               => __DIR__ . '/src/Galaxy/Mapper/SystemFactory.php',
    'Galaxy\Mapper\SystemObject'                => __DIR__ . '/src/Galaxy/Mapper/SystemObject.php',
    'Galaxy\Mapper\SystemObjectFactory'         => __DIR__ . '/src/Galaxy/Mapper/SystemObjectFactory.php',
    'Galaxy\Service\Gateway'                    => __DIR__ . '/src/Galaxy/Service/Gateway.php',
    'Galaxy\Service\GatewayFactory'             => __DIR__ . '/src/Galaxy/Service/GatewayFactory.php',
    'Galaxy\Table\Colony'                       => __DIR__ . '/src/Galaxy/Table/Colony.php',
    'Galaxy\Table\System'                       => __DIR__ . '/src/Galaxy/Table/System.php',
    'Galaxy\Table\SystemObject'                 => __DIR__ . '/src/Galaxy/Table/SystemObject.php',
);