<div class="row">
    <div class="accordion" id="inbox-accordion">
      <?php foreach ($messages as $message): ?>
        <div id="message-<?php echo $message->getId() ?>" class="accordion-group">
            <div class="accordion-heading row-fluid">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#inbox-accordion" href="#collapse-message-<?php echo $message->getId() ?>">
                    <span class="col-md-1"><i class="glyphicon glyphicon-time"></i> <?php echo $message->getTick() ?></span>
                    <span class="col-md-1"><strong><?php echo $message->getSender() ?>:</strong></span>
                    <span class="col-md-10"><?php echo $message->getSubject() ?></span>
                </a>
            </div>
            <div id="collapse-message-<?php echo $message->getId() ?>" class="accordion-body collapse row-fluid">
                <div class="accordion-inner">
                    <div class="col-md-2">...</div>
                    <div class="col-md-10">
                      <p><?php echo $message->getText() ?></p>
                      <br />
                      <span class="message-options" id="message-<?php echo $message->getId() ?>-options">
                      <a href="#" class="btn disabled" data-placement="bottom" rel="tooltip" data-original-title="<?php echo $this->translate('react_positive')?>"><i class="glyphicon glyphicon-thumbs-up"></i></a>
                      <a href="#" class="btn disabled" data-placement="bottom" rel="tooltip" data-original-title="<?php echo $this->translate('react_positive_and_answer')?>"><i class="glyphicon glyphicon-thumbs-up"></i> + <i class="glyphicon glyphicon-envelope"></i></a>
                      <a href="#" class="btn disabled" data-placement="bottom" rel="tooltip" data-original-title="<?php echo $this->translate('react_neutral_and_answer')?>"><i class="glyphicon glyphicon-envelope"></i></a>
                      <a href="#" class="btn disabled" data-placement="bottom" rel="tooltip" data-original-title="<?php echo $this->translate('react_negative')?>"><i class="glyphicon glyphicon-thumbs-down"></i></a>
                      <a href="#" class="btn disabled" data-placement="bottom" rel="tooltip" data-original-title="<?php echo $this->translate('react_negative_and_answer')?>"><i class="glyphicon glyphicon-thumbs-down"></i> + <i class="glyphicon glyphicon-envelope"></i></a>
                      <a href="<?php echo $this->url('messages', array('action' => 'remove', 'id' => $message->getId())) ?>"  class="btn secondary-nav" data-placement="bottom" rel="tooltip" data-original-title="löschen"><i class="glyphicon glyphicon-remove"></i> löschen</a>
                      </span>
                    </div>
                </div>
            </div>
        </div>
      <?php endforeach; ?>
    </div>

    <ul class="pagination">
        <li><a href="#">&laquo;</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">&raquo;</a></li>
    </ul>
</div><!--/row-->
