<div class="row-fluid">
    <ul class="nav nav-tabs">
        <li class="active"><a href="<?= $this->url('innn/message', array('action' => 'new')) ?>">New Message</a></li>
        <li><a href="<?= $this->url('innn/message', array('action' => 'inbox')) ?>">Inbox</a></li>
        <li><a href="<?= $this->url('innn/message', array('action' => 'outbox')) ?>">Outbox</a></li>
        <li class="secondary-nav"><a href="<?= $this->url('innn/message', array('action' => 'archive')) ?>">Archive</a></li>
    </ul>

</div><!--/row-->