<div class="row">
    <div class="tabbable tabs-left">
      <ul class="nav nav-tabs" id="myTab">
        <li class="active"><a href="#msg-to-user" data-toggle="tab">... to User</a></li>
        <li class="disabled"><a href="#msg-to-faction" data-toggle="tab">... to Faction</a></li>
        <li>&nbsp;</li>
        <li>&nbsp;</li>
        <li class="disabled"><a href="#msg-to-innn">... to INNN</a></li>
        <li>&nbsp;</li>
        <li class="disabled"><a href="#msg-to-support">... to Support</a></li>
      </ul>
      <div class="tab-content">

        <div class="tab-pane active" id="msg-to-user">
        <?php echo $this->form($this->form->prepare()); ?>
        </div>

        <div class="tab-pane" id="msg-to-faction">

        </div>

        <div class="tab-pane" id="msg-to-innn">

        </div>

        <div class="tab-pane" id="msg-to-support">

        </div>
      </div>

    </div>

</div><!--/row-->
