<div class="row">
    <div class="col-12">
      <ul class="nav nav-tabs mb-3" id="myTab" role="tablist">
        <li class="nav-item" role="presentation">
          <button class="nav-link active" data-bs-toggle="tab" data-bs-target="#msg-to-user" type="button">... to User</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link disabled" type="button">... to Faction</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link disabled" type="button">... to INNN</button>
        </li>
        <li class="nav-item" role="presentation">
          <button class="nav-link disabled" type="button">... to Support</button>
        </li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane fade show active" id="msg-to-user" role="tabpanel">
          <?php echo $this->form($this->form->prepare()); ?>
        </div>
        <div class="tab-pane fade" id="msg-to-faction" role="tabpanel"></div>
        <div class="tab-pane fade" id="msg-to-innn" role="tabpanel"></div>
        <div class="tab-pane fade" id="msg-to-support" role="tabpanel"></div>
      </div>
    </div>
</div>
