<div class="row-fluid">
    <div class="accordion" id="inbox-accordion">
    <? foreach ($messages as $message): ?>
        <div class="accordion-group">
            <div class="accordion-heading row-fluid">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#inbox-accordion" href="#collapse-message-<?= $message['id'] ?>">
                    <span class="span1"><i class="icon-time"></i> <?= $message['tick'] ?></span>
                    <span class="span1"><strong>an <?= $message['recipient_id'] ?>:</strong></span>
                    <span class="span10"><?= $message['subject'] ?></span>
                </a>
            </div>
            <div id="collapse-message-<?= $message['id'] ?>" class="accordion-body collapse row-fluid">
                <div class="accordion-inner">
                    <div class="span2">...</div>
                    <div class="span10">
                      <p><?= $message['text'] ?></p>
                      <br />
                      <a href="#" class="btn disabled" data-placement="bottom" rel="tooltip" data-original-title="positiv reagieren"><i class="icon-thumbs-up"></i></a>
                      <a href="#" class="btn disabled" data-placement="bottom" rel="tooltip" data-original-title="positiv reagieren"><i class="icon-thumbs-up"></i> + <i class="icon-envelope"></i></a>
                      <a href="#" class="btn disabled" data-placement="bottom" rel="tooltip" data-original-title="positiv reagieren"><i class="icon-envelope"></i></a>
                      <a href="#" class="btn disabled" data-placement="bottom" rel="tooltip" data-original-title="positiv reagieren"><i class="icon-thumbs-down"></i></a>
                      <a href="#" class="btn disabled" data-placement="bottom" rel="tooltip" data-original-title="positiv reagieren"><i class="icon-thumbs-down"></i> + <i class="icon-envelope"></i></a>
                    </div>
                </div>
            </div>
        </div>
    <? endforeach ?>
    </div>
</div><!--/row-->