<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

/**
 * A13/P2a: bar offers now store BASE terms only; the Konsul rate (Handelsvorteil)
 * is applied at display/accept time. Offers generated before this change still
 * carry the rate baked into their amounts, so accepting one would apply it a
 * second time.
 *
 * Deletes every still-open (unaccepted) offer that could carry a baked-in rate:
 * generic guest offers (visit_id IS NULL) and Corvan's Credits->goods buy offers.
 * Corvan's Organika->Credits sell lots (visit_id set, Credits on the Get side)
 * never had a rate baked in and stay. Accepted offers are history and stay.
 * Guest offers are regenerated by the tick; a Corvan buy offer of a still-running
 * visit is simply gone (his sell lots and special inventory remain).
 *
 * Data-only, one-way: down() cannot restore the deleted offers.
 */
return new class extends Migration
{
    private const RES_CREDITS = 1;

    public function up(): void
    {
        DB::table('bar_offers')
            ->where('is_accepted', false)
            ->where(function ($q): void {
                $q->whereNull('visit_id')
                    ->orWhere('give_resource_id', self::RES_CREDITS);
            })
            ->delete();
    }

    public function down(): void
    {
        // Irreversible data cleanup — nothing to restore.
    }
};
