<h1>Technologies</h1>
<p>
    <a href="<?php echo $this->url('techtree',array('controller'=>'technology','action'=>'add'));?>">Add new technology</a>
</p>

<table class="table table-striped table-bordered">
<tr>
    <th>id</th>
    <th>type</th>
    <th>purpose</th>
    <th>name</th>
    <th>prime_colony_only<br /><small>1 = nur auf Primärkol. baubar, 0 = auf allen Kol.</small></th>
    <th>stage</th>
    <th>graph_row</th>
    <th>graph_column</th>
    <th>max_level</th>
    <th>build_time<br /><small>ticks needed to build or research this tech</small></th>
    <th>decay<br /><small>decay time in ticks</small></th>
    <th>tradeable</th>
    <th>moving_speed<br /><small>moving speed per tick (primarily for ships)</small></th>
    <th>-</th>
</tr>
<?php foreach ($technologies as $tech) : ?>
<tr>
    <td><?php echo $this->escapeHtml($tech->id);?></td>
    <td><?php echo $this->escapeHtml($tech->type);?></td>
    <td><?php echo $this->escapeHtml($tech->purpose);?></td>
    <td><?php echo $this->escapeHtml($tech->name);?></td>
    <td><?php echo $this->escapeHtml($tech->prime_colony_only);?></td>
    <td><?php echo $this->escapeHtml($tech->stage);?></td>
    <td><?php echo $this->escapeHtml($tech->graph_row);?></td>
    <td><?php echo $this->escapeHtml($tech->graph_column);?></td>
    <td><?php echo $this->escapeHtml($tech->max_level);?></td>
    <td><?php echo $this->escapeHtml($tech->build_time);?></td>
    <td><?php echo $this->escapeHtml($tech->decay);?></td>
    <td><?php echo $this->escapeHtml($tech->tradeable);?></td>
    <td><?php echo $this->escapeHtml($tech->moving_speed);?></td>
    <td>
        <a href="<?php echo $this->url('techtree', array('action'=>'edit', 'id' => $tech->id));?>">Edit</a>
        <a href="<?php echo $this->url('techtree', array('action'=>'delete', 'id' => $tech->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
