<!-- Modal -->
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
        <h3 class="modal-title" id="myModalLabel"><?php echo $this->translate($personell['name']) ?> (<?php echo $personell['level'] ?>)
            <small class="text-muted fs-6">(<?php echo $this->translate('types_personell') ?>/<?php echo $this->translate('purposes_' . $personell['purpose']) ?>)</small></h3>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Schließen"></button>
    </div>
    <div class="modal-body">
        <!-- Description -->
        <p><?php echo $this->translate('desc_'.$personell['name'])?></p>

        <!-- Costs -->
        <h4><?php echo $this->translate('costs and requirements') ?></h4>

        <table class="table">
            <tr>
            <td><i class="<?php echo ($required_resources_check==true)? 'bi bi-check-lg text-success' : 'bi bi-x-lg text-danger' ?>"></i></td>
            <td>
            <?php
                foreach ($costs as $cost):
                    $resource = $resources[ $cost->getResourceId() ];
                    $name = $resource['name'];
                    $abbreviation =  $resource['abbreviation'];
                    $class  = $resource['icon'];
                    $amount = $cost->getAmount();
                    if ($amount > 0):
                        echo '<a data-bs-placement="bottom" data-bs-toggle="tooltip" href="#" title="'.$name.'">';
                        echo '<i class="'.$class.'">'.$abbreviation.'</i> '.$amount.'</a> ';
                    endif;
                endforeach;
            ?>
            </td>
            </tr>
            <?php if (!empty($personell['required_building_id'])): ?>
            <tr>
                <td><?php echo $required_buildings_check ? '<i class="bi bi-check-lg text-success"></i>' : '<i class="bi bi-x-lg text-danger"></i>'; ?></td>
                <td><?php echo $this->translate( $buildings[ $personell['required_building_id'] ]['name'] ) ?> (<?php echo $personell['required_building_level'] ?>)</td>
            </tr>
            <?php endif; ?>
            <tr>
                <td colspan="2">
                    <?php if (($required_buildings_check && $required_resources_check) == false):?>
                    <a id="personell-<?php echo $personell['id'] ?>|levelup" class="btn disabled">anheuern</a>
                    <?php else:?>
                    <a id="personell-<?php echo $personell['id'] ?>|levelup" class="btn btn-success">anheuern</a>
                    <?php endif;?>
                    <a id="personell-<?php echo $personell['id'] ?>|leveldown" class="btn btn-danger">feuern</a>
                </td>
            </tr>
        </table>
        <?php if (is_array($message)): ?>
        <div class="alert alert-<?php echo $message[0] ?>">
            <p><i class="bi bi-exclamation-triangle"></i><?php echo $message[1] ?></p>
        </div>
        <?php endif;?>

    </div>
  </div>
</div>
