<!-- Modal -->
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel"><?php echo $this->translate($research['name']) ?> (<?php echo $research['level'] ?>)
            <small>(<?php echo $this->translate('types_' . 'research') ?>/<?php echo $this->translate('purposes_' . $research['purpose']) ?>)</small>
        </h3>
    </div>
    <div class="modal-body">
        <!-- Description -->
        <p><?php echo $this->translate('desc_'.$research['name'])?></p>
        freie AP: <?php echo $ap_available ?>
        <!-- Data -->

        <!-- Costs -->
        <h4><?php echo $this->translate('costs and requirements') ?></h4>

        <table class="table">

        <tr>
        <td><i class="<?php echo ($required_resources_check==true)? 'glyphicon glyphicon-ok' : 'glyphicon glyphicon-remove' ?>"></i></td>
        <td>
        <?php
        foreach ($costs as $cost):
            $resource = $resources[ $cost->getResourceId() ];
            $name = $resource['name'];
            $abbreviation =  $resource['abbreviation'];
            $class  = $resource['icon'];
            $amount = $cost->getAmount();
            if ($amount > 0):
                echo '<a data-placement="bottom" rel="tooltip" href="#" data-original-title="'.$name.'">';
                echo '<i class="'.$class.'">'.$abbreviation.'</i> '.$amount.'</a> ';
            endif;
        endforeach;
        ?>
        </td>
        </tr>
        <?php if (!empty($research['required_building_id'])): ?>
        <tr>
            <td><?php echo $required_buildings_check ? '<i class="glyphicon glyphicon-ok"></i>' : '<i class="glyphicon glyphicon-remove"></i>'; ?></td>
            <td><?php echo $this->translate( $buildings[ $research['required_building_id'] ]['name'] ) ?> (<?php echo $research['required_building_level'] ?>)</td>
        </tr>
        <?php endif; ?>
        <tr>
           <td colspan="2">
           <?php $poss = array_key_exists($research['id'], $possessions ) ? $possessions[$research['id']] : null; ?>
           <?php echo $this->partial('partial/techstatus_bar', array('tech'=>$research, 'type'=>'research', 'poss'=>$poss, 'ap_spend'=> $research['ap_spend'], 'ap_available'=> $ap_available)) ?>
           <?php $class = ($research['status_points'] == 0 && $research['level'] > 0) ? 'btn-danger': 'disabled';?>
           <a id="research-<?php echo $research['id'] ?>|leveldown"  class="btn <?php echo $class ?>" >abreißen</a>
           </td>
        </tr>
        <tr>
            <td colspan="2">
            <?php echo $this->partial('partial/techlevelup_bar', array('tech'=>$research, 'type'=>'research', 'ap_spend'=> $research['ap_spend'], 'ap_available'=> $ap_available)) ?>
            <?php $class = ($research['ap_spend'] >= $research['ap_for_levelup']) ? 'btn-success': 'disabled';?>
            <?php if (($required_buildings_check && $required_resources_check) == false): ?>
            <a id="research-<?php echo $research['id'] ?>|levelup" class="btn disabled" >ausbauen</a>
            <?php else: ?>
            <a id="research-<?php echo $research['id'] ?>|levelup" class="btn <?php echo $class ?>" >ausbauen</a>
            <?php endif; ?>
            </td>
        </tr>
        </table>
        <?php if (is_array($message)): ?>
        <div class="alert alert-<?php echo $message[0] ?>">
            <p><i class="icon glyphicon glyphicon-error"></i><?php echo $message[1] ?></p>
        </div>
        <?php endif;?>
    <!--<div class="modal-footer">
        <button class="btn btn-primary">Save changes</button>
    </div>-->
<!--</div>-->
  </div>
</div>
