<!-- Modal -->
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
        <h3 class="modal-title" id="myModalLabel"><?php echo $this->translate($ship['name']) ?> (<?php echo $ship['level'] ?>)
            <small class="text-muted fs-6">(<?php echo $this->translate('types_ship') ?>/<?php echo $this->translate('purposes_' . $ship['purpose']) ?>)</small></h3>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Schließen"></button>
    </div>
    <div class="modal-body">
        <!-- Description -->
        <p><?php echo $this->translate('desc_'.$ship['name'])?></p>
        freie AP: <?php echo $ap_available ?>

        <!-- Costs -->
        <h4><?php echo $this->translate('costs and requirements') ?></h4>

        <table class="table">
            <tr>
            <td><i class="<?php echo ($required_resources_check==true)? 'bi bi-check-lg text-success' : 'bi bi-x-lg text-danger' ?>"></i></td>
            <td>
            <?php
                foreach ($costs as $cost):
                    $resource = $resources[ $cost->getResourceId() ];
                    $name = $resource['name'];
                    $abbreviation =  $resource['abbreviation'];
                    $class  = $resource['icon'];
                    $amount = $cost->getAmount();
                    if ($amount > 0):
                        echo '<a data-bs-placement="bottom" data-bs-toggle="tooltip" href="#" title="'.$name.'">';
                        echo '<i class="'.$class.'">'.$abbreviation.'</i> '.$amount.'</a> ';
                    endif;
                endforeach;
            ?>
            </td>
            </tr>
            <?php if (!empty($ship['required_building_id'])): ?>
            <tr>
                <td><?php echo $required_buildings_check ? '<i class="bi bi-check-lg text-success"></i>' : '<i class="bi bi-x-lg text-danger"></i>'; ?></td>
                <td><?php echo $this->translate( $buildings[ $ship['required_building_id'] ]['name'] ) ?> (<?php echo $ship['required_building_level'] ?>)</td>
            </tr>
            <?php endif; ?>
            <?php if (!empty($ship['required_research_id'])): ?>
            <tr>
                <td><?php echo $required_researches_check ? '<i class="bi bi-check-lg text-success"></i>' : '<i class="bi bi-x-lg text-danger"></i>'; ?></td>
                <td><?php echo $this->translate( $researches[ $ship['required_research_id'] ]['name'] ) ?> (<?php echo $ship['required_researches_level'] ?>)</td>
            </tr>
            <?php endif; ?>
        <tr>
           <td colspan="2">
           <?php $poss = array_key_exists($ship['id'], $possessions ) ? $possessions[$ship['id']] : null; ?>
           <?php echo $this->partial('partial/techstatus_bar', array('tech'=>$ship,  'type'=>'ship', 'poss'=>$poss, 'ap_spend'=> $ship['ap_spend'], 'ap_available'=> $ap_available)) ?>
           <?php $class = ($ship['status_points'] == 0 && $ship['level'] > 0) ? 'btn-danger': 'disabled';?>
           <a id="ship-<?php echo $ship['id'] ?>|leveldown"  class="btn <?php echo $class ?>" >abreißen</a>
           </td>
        </tr>
            <tr>
                <td colspan="2">
                <?php echo $this->partial('partial/techlevelup_bar', array('tech'=>$ship, 'type'=>'ship', 'ap_spend'=> $ship['ap_spend'], 'ap_available'=> $ap_available)) ?>
                <?php $class = ($ship['ap_spend'] >= $ship['ap_for_levelup']) ? 'btn-success': 'disabled';?>
                <a id="ship-<?php echo $ship['id'] ?>|levelup" class="btn <?php echo $class ?>" >ausbauen</a>
                </td>
            </tr>
        </table>
        <?php if (is_array($message)): ?>
        <div class="alert alert-<?php echo $message[0] ?>">
            <p><i class="bi bi-exclamation-triangle"></i><?php echo $message[1] ?></p>
        </div>
        <?php endif;?>

    </div>
  </div>
</div>
