<!-- Modal -->
<div id="techModal" class="modal hide fade in" aria-hidden="false" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" style="display: block;">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel"><?= $this->translate($tech->name) ?> (<?= $level ?>)
            <small>(<?= $this->translate('types_' . $tech->type) ?>/<?= $this->translate('purposes_' . $tech->purpose) ?>)</small></h3>
    </div>
    <div class="modal-body">
        <!-- Description -->
        <p><?= $this->translate('desc_'.$tech->name)?></p>
        freie AP: <?= $ap_available ?>
        <!-- Data -->
        <?= ($tech->max_level > 0) ? '<span class="label">' . $this->translate('max_level') . ': '. $tech->max_level . '</span>' : '' ?>
        <?= ($tech->type == 'ship') ? '<span class="label">' . $this->translate('moving_speed') . ': '. $tech->moving_speed . '</span>' : '' ?>
        <?= ($tech->tradeable) ? '<span class="label">' . $this->translate('tradeable') . '</span>' : '' ?>

        <!-- Costs -->
        <h4><?= $this->translate('costs and requirements') ?></h4>

        <table class="table">
        <? if (!empty($costs)): ?>
        <tr>
        <td><i class="<?= ($required_resources_check==true)? 'icon-ok' : 'icon-remove' ?>"></i></td>
        <td>
        <?php
        foreach ($costs as $cost):
            $resource = $resources[ $cost['resource_id'] ];
            $name = $resource['name'];
            $abbreviation =  $resource['abbreviation'];
            $class  = $resource['icon'];
            $amount = $cost['amount'];
            if ($amount > 0):
                echo '<a data-placement="bottom" rel="tooltip" href="#" data-original-title="'.$name.'">';
                echo '<i class="'.$class.'">'.$abbreviation.'</i> '.$amount.'</a> ';
            endif;
        endforeach;
        ?>
        </td>
        </tr>
        <? endif;
        foreach ($requirements as $req):
            if (isset($possessions[ $req['required_tech_id'] ]) && $possessions[ $req['required_tech_id'] ]['level'] >= $req['required_tech_level']):
                $fullfilled = '<i class="icon-ok"></i>';
            else:
                $fullfilled = '<i class="icon-remove"></i>';
            endif;
        ?>
        <tr>
            <td><?= $fullfilled ?></td>
            <td><?= $this->translate( $techs[ $req['required_tech_id'] ]['name'] ) ?> (<?= $req['required_tech_level'] ?>)</td>
        </tr>
        <?php endforeach;
        if ($tech->type != 'advisor'):?>
        <tr>
           <td colspan="2">
           <?php $poss = array_key_exists($tech->id, $possessions ) ? $possessions[$tech->id] : null; ?>
           <?= $this->partial('partial/techstatus_bar', array('tech'=>$tech, 'poss'=>$poss, 'ap_spend'=> $ap_spend, 'ap_available'=> $ap_available)) ?>
           <? $class = ($status_points == 0 && $level > 0) ? 'btn-danger': 'disabled';?>
           <a id="tech-<?= $tech->id ?>|leveldown"  class="btn <?= $class ?>" >abreißen</a>
           </td>
        </tr>
        <tr>
            <td colspan="2">
            <?= $this->partial('partial/techlevelup_bar', array('tech'=>$tech, 'ap_spend'=> $ap_spend, 'ap_available'=> $ap_available)) ?>
            <? $class = ($ap_spend >= $tech->ap_for_levelup) ? 'btn-success': 'disabled';?>
            <a id="tech-<?= $tech->id ?>|levelup" class="btn <?= $class ?>" >ausbauen</a>
            </td>
        </tr>
        <? else:?>
        <tr>
            <td colspan="2">
                <? if (($required_techs_check || $required_resources_check || $ap_spend_check) == false):?>
                <a id="tech-<?= $tech->id ?>|levelup" class="btn disabled">anheuern</a>
                <? else: ?>
                <a id="tech-<?= $tech->id ?>|levelup" class="btn btn-success">anheuern</a>
                <? endif; ?>
                <a id="tech-<?= $tech->id ?>|leveldown" class="btn btn-danger">feuern</a>
            </td>
        </tr>
        <? endif;?>

        </table>
        <?php if (is_array($message)): ?>
        <div class="alert alert-<?= $message[0] ?>">
            <p><i class="icon icon-error"></i><?= $message[1] ?></p>
        </div>
        <?php endif;?>

    </div>

    <!--<div class="modal-footer">
        <button class="btn btn-primary">Save changes</button>
    </div>-->
</div>