<div class="row-fluid resource-bar">
    <a data-placement="bottom" rel="tooltip" href="#" data-original-title="Ticks"><i class="icon-time"></i> 5 </a>
    <a data-placement="bottom" rel="tooltip" href="#" data-original-title="Credits"><i class="resicon-credits">Cr</i> 123456 </a>
    <a data-placement="bottom" rel="tooltip" href="#" data-original-title="Supply"><i class="resicon-supply">Sup</i> 155/322 </a>
    <a data-placement="bottom" rel="tooltip" href="#" data-original-title="Moral"><i class="resicon-moral">Mor</i> gut </a>
    <a data-placement="bottom" rel="tooltip" href="#" data-original-title="Eisen"><i class="resicon-iron">I</i> 12345 </a>
    <a data-placement="bottom" rel="tooltip" href="#" data-original-title="Wasser"><i class="resicon-water">W</i> 12345 </a>
    <a data-placement="bottom" rel="tooltip" href="#" data-original-title="Silikate"><i class="resicon-silicates">S</i> 12345 </a>
    <a data-placement="bottom" rel="tooltip" href="#" data-original-title=""><i class="resicon-ena">E</i> 12345 </a>
    <a data-placement="bottom" rel="tooltip" href="#" data-original-title=""><i class="resicon-aku">A</i> 12345 </a>
    <a data-placement="bottom" rel="tooltip" href="#" data-original-title=""><i class="resicon-lho">L</i> 12345 </a>
</div>