<?php

$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);
$basePath = $this->basePath();

//Twitter Bootstrap styles
$this->headLink()->appendStylesheet($basePath . '/vendor/bootstrap/dist/css/bootstrap.min.css');

$this->headLink()->appendStylesheet($basePath . '/vendor/ngm/css/ngm.css');
//Add your own style here
$this->headLink()->appendStylesheet($basePath . '/css/style.css');

//jQuery and Twitter Bootstrap JS libraries
$this->inlineScript()->appendFile($basePath . '/vendor/jquery/dist/jquery.min.js');
$this->inlineScript()->appendFile($basePath . '/vendor/bootstrap/dist/js/bootstrap.min.js');
#$this->inlineScript()->appendFile($basePath . '/vendor/bootbox/bootbox.js');
$this->inlineScript()->appendFile($basePath . '/vendor/ngm/js/ngm.js');
$this->inlineScript()->appendFile($basePath . '/js/jquery.bootstrap-growl.min.js');
$this->inlineScript()->appendFile($basePath . '/js/techtree.js');
$this->inlineScript()->appendFile($basePath . '/js/nouron.js');
$this->inlineScript()->appendFile($basePath . '/js/innn.js');
$this->inlineScript()->appendFile($basePath . '/js/galaxy.js');
$this->inlineScript()->appendFile($basePath . '/js/fleets.js');
$this->inlineScript()->appendFile($basePath . '/js/trade.js');

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('') ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle(); ?>
    <!-- Scripts -->
    <?php echo $this->headScript() ?>
  </head>

  <body>
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Nouron') ?></a>
          </div>
          <?php if ($this->zfcUserIdentity()): ?>
          <?php     echo  $this->navigation('navigation')->menu()->setMaxDepth(0)->setUlClass('nav navbar-nav'); ?>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li class="dropdown"><a data-toggle="dropdown" class="dropdown-toggle" href="<?php echo $this->url('settings') ?>"><?php echo $this->zfcUserIdentity()->getUsername(); ?> <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                      <li><a href="<?php echo $this->url('zfcuser/changepassword') ?>">Passwort ändern</a></li>
                      <li><a href="<?php echo $this->url('zfcuser/changeemail') ?>">Email ändern</a></li>
                  </ul>
              </li>
              <li><a href="<?php echo $this->url('zfcuser/logout') ?>"><i class="glyphicon glyphicon-off"></i> <?php echo $this->translate('logout') ?></a></li>
            </ul>
          </div>
          <?php else: ?>
          <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><a href="<?php echo $this->url('zfcuser/login') ?>"><?php echo $this->translate('Login') ?></a></li>
              <li><a href="<?php echo $this->url('zfcuser/register') ?>"><?php echo $this->translate('Register') ?></a></li>
            </ul>
          </div>
          <?php endif; ?>
        </div>
    </nav>
    <div class="container">
        <?php
        // flash messages if any
        // First get the viewmodel and all its children (ie the actions viewmodel)
        $children = $this->viewModel()
                         ->getCurrent()
                         ->getChildren();
        $ourView  = $children[0];

        if ($this->zfcUserIdentity() && isset($ourView->possessions)):
            echo $this->resources($ourView->possessions); ?>
        <hr />
        <?php endif; ?>

        <div class="flashMessages" id="flashMessages">
        <?php if (isset($ourView->flashMessages) && count($ourView->flashMessages)) :
            foreach ($ourView->flashMessages as $message) : ?>
            <div class="alert"><?php echo $message; ?></div>
            <?php endforeach;
        endif; ?>
        </div>
        <?php echo $this->navigation()
                        ->menu()
                        ->setUlClass('nav nav-tabs')
                        ->setOnlyActiveBranch(true)
                        ->setRenderParents(false)
                        ->setMinDepth(1)
                        ->setMaxDepth(1);
        echo $this->content; ?>
        <hr />
    </div><!-- /container -->
    <?php echo $this->inlineScript(); ?>
    <script  type="text/javascript">
    $(document).ready(function() {
        if ($('#colony').length > 0) {techtree.init(); }
        if ($('#fleetlist').length > 0) {fleetlist.init(); }
        if ($('#fleetconfig').length > 0)  {fleetconfig.init(); }
        if ($('#trade').length > 0)  {trade.init();  }

        if ($('#ngm-map').length > 0)  {

            var config = {
              'dataSourceUri': "/galaxy/json/getmapdata/%s/%s",
              'selector': '#ngm-map',
              'eventCallbacks': {
                  'fieldSelect': displayFieldInformations,
              },
                // initial center coordinates - all other coordinates are calculated on
                // these values as base
              'center' : [<?= $ourView->x ?>,<?= $ourView->y ?>],
              'layers': [
                  {'name': 'misc', 'class': 'ngm-misc-layer', 'objectDefaultShape': 'square', 'cache':'enabled'},
                  {'name': 'planets', 'class': 'ngm-planets-layer', 'objectDefaultShape': 'circle', 'cache': 'enabled'},
                  {'name': 'stations', 'class': 'ngm-stations-layer', 'objectDefaultShape': 'square', 'cache': 'enabled'},
                  {'name': 'ships', 'class': 'ngm-ships-layer', 'objectDefaultShape': 'triangle'}
              ],
              'borderWidth': '1px',
              'borderColor': '#999',
              'backgroundImageUrl': '/img/starfields/starfield_blue.jpg'
            };

            ngm.configurate(config);
            ngm.init();

            window.onresize = function(event) {
                console.log("resize");
                ngm.init();
            };

            function displayFieldInformations(event) {

            }
        }
    });

    </script>
  </body>
</html>
