<?php if ($this->pageCount>1): ?>
<?php
$urlhelperparams = array(
    'action' => $this->action,
    'page' => 1
);
?>
<ul class="pagination">
    <!-- Vorheriger Seitenlink -->
    <?php if (isset($this->previous)): ?>
        <?php $urlhelperparams['page'] = $this->previous; ?>
        <li><a href="<?php echo $this->url($this->route, $urlhelperparams); ?>">&laquo; Zurück</a></li>
    <?php else: ?>
        <li class="disabled"><span>&laquo; Zurück</span></li>
    <?php endif; ?>

    <!-- Anzahl an Seitenlinks -->
    <?php foreach ($this->pagesInRange as $page): ?>
      <?php if ($page != $this->current): ?>
        <li><a href="<?php echo $this->url($this->route, $urlhelperparams); ?>"><?php echo $page; ?></a></li>
      <?php else: ?>
        <li class="active"><span ><?php echo $page; ?></span></li>
      <?php endif; ?>
    <?php endforeach; ?>

    <!-- Nächster Seitenlink -->
    <?php if (isset($this->next)): ?>
        <?php $urlhelperparams['page'] = $this->next; ?>
        <li><a href="<?php echo $this->url($this->route, $urlhelperparams); ?>">Vor  &raquo;</a></li>
    <?php else: ?>
        <li><span class="disabled">Vor &raquo;</span></li>
    <?php endif; ?>
</ul>
<?php endif; ?>
