<!--
Siehe http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->

<?php if ($this->pageCount>1): ?>
<div class="pagination">
    <ul>
    <!-- Vorheriger Seitenlink -->
    <?php if (isset($this->previous)): ?>
        <li><a href="<?= $this->url($this->route, array('page' => $this->previous)); ?>">&lt; Zurück</a></li>
    <?php else: ?>
        <li><span class="disabled">&lt; Zurück</span></li>
    <?php endif; ?>

    <!-- Anzahl an Seitenlinks -->
    <?php foreach ($this->pagesInRange as $page): ?>
      <?php if ($page != $this->current): ?>
        <li><a href="<?= $this->url($this->route, array('page' => $page)); ?>"><?= $page; ?></a></li>
      <?php else: ?>
        <li><span class="disabled"><?= $page; ?></span></li>
      <?php endif; ?>
    <?php endforeach; ?>

    <!-- Nächster Seitenlink -->
    <?php if (isset($this->next)): ?>
        <li><a href="<?= $this->url($this->route, array('page' => $this->next)); ?>">Vor &gt;</a></li>
    <?php else: ?>
        <li><span class="disabled">Vor &gt;</span></li>
    <?php endif; ?>
    </ul>
</div>
<?php endif; ?>
