<?php if ($this->success): ?>
<div class="alert alert-success">Flotte wurde erstellt!</div>
<?php endif; ?>

<?= $this->partial('partial/_switch_tech_display') ?>

<div id="fleet">
    <div class="hidden" id="fleet_id"><?= $fleet['id']?></div>
    <div class="hidden" id="colony_id"><?= $colony['id']?></div>
    <div class="row-fluid">
        <div class="span6" style="text-align: center"><h3><?= $this->translate('colony') ?></h3></div>
        <div class="span3"><h3><?= $this->translate('fleet') ?></h3></div>
        <div class="span3"><h3><?= $this->translate('fleet') ?>(<?= $this->translate('cargo') ?>)</h3></div>
    </div>
<? if ($fleetIsInColonyOrbit):
    foreach ($techs as $techId => $tech):
        if ($tech["tradeable"] == 1):
?>
    <div class="row-fluid item tech <?= $tech['type'] ?>" id="tech-<?= $techId ?>">
        <div class="span3" style="text-align: right"><?= $this->translate($tech["name"]) ?> <div class="tech <?= $tech['type']?>" style="display:inline-block;height:0.9em;width:0.9em;border:1px solid #222;"> </div></div>
        <div class="span1 countOnColony" id="techOnColony-<?= $techId ?>">0</div>
        <? if ( in_array(strtolower($tech['type']), array('ship', 'advisor')) ): ?>
        <div class="span1 countInFleet"  id="techInFleet-<?= $techId ?>">0</div>
        <div class="span3">
            <a class="btn btn-small btn-warning transfer">-10</a>
            <a class="btn btn-small btn-warning transfer">-5</a>
            <a class="btn btn-small btn-warning transfer">-1</a>
            <a class="btn btn-small btn-success transfer">+1</a>
            <a class="btn btn-small btn-success transfer">+5</a>
            <a class="btn btn-small btn-success transfer">+10</a>
        </div>
        <? else: ?>
        <div class="span4"></div>
        <? endif; ?>
        <div class="span1 countInFleetCargo" id="techInFleetCargo-<?= $techId ?>">0</div>
        <div class="span3">
            <a class="btn btn-small btn-warning transfer cargo">-10</a>
            <a class="btn btn-small btn-warning transfer cargo">-5</a>
            <a class="btn btn-small btn-warning transfer cargo">-1</a>
            <a class="btn btn-small btn-success transfer cargo">+1</a>
            <a class="btn btn-small btn-success transfer cargo">+5</a>
            <a class="btn btn-small btn-success transfer cargo">+10</a>
        </div>
    </div>
<?      endif;
    endforeach;

    foreach ($resources as $resId => $resource):
        if ($resource["is_tradeable"] == 1):
?>
    <div class="row-fluid item resource" id="resource-<?= $resId ?>">
        <div class="span3" style="text-align: right"><?= $this->translate($resource["name"]) ?></div>
        <div class="span1 countOnColony" id="resourceOnColony-<?= $resId ?>">0</div>
        <div class="span4"></div>
        <div class="span1 countInFleetCargo" id="resourceInFleetCargo-<?= $resId ?>">0</div>
        <div class="span3">
            <a class="btn btn-small btn-warning transfer cargo">-100</a>
            <a class="btn btn-small btn-warning transfer cargo">-50</a>
            <a class="btn btn-small btn-warning transfer cargo">-10</a>
            <a class="btn btn-small btn-success transfer cargo">+10</a>
            <a class="btn btn-small btn-success transfer cargo">+50</a>
            <a class="btn btn-small btn-success transfer cargo">+100</a>
        </div>

    </div>
<?      endif;
    endforeach;
endif; ?>
</div>
