<?php foreach ($techs as $techId => $tech): ?>
<div class="row item <?php echo $type ?>" id="<?php echo $type . '-' . $techId ?>">
    <div class="col-4 transferButtons text-end">
        <button class="btn btn-sm btn-secondary" value="-10">10</button>
        <button class="btn btn-sm btn-secondary" value="-5">5</button>
        <button class="btn btn-sm btn-secondary" value="-1">1</button>
    </div>
    <div class="col-1 countOnColony <?php echo $type . 'OnColony-' . $techId ?>">0</div>
    <div class="col-2 text-center"><?php echo $this->translate($tech["name"]) ?></div>
    <div class="col-1 countInFleet <?php echo $type . 'InFleet-' . $techId ?>">0</div>
    <div class="col-4 transferButtons">
        <button class="btn btn-sm btn-secondary" value="1">1</button>
        <button class="btn btn-sm btn-secondary" value="5">5</button>
        <button class="btn btn-sm btn-secondary" value="10">10</button>
    </div>
</div>
<?php endforeach; ?>
