<? foreach ($techs as $techId => $tech): ?>
<div class="row-fluid item <?= $type ?>" id="<?= $type . '-' . $techId ?>">
    <div class="span4" style="text-align: right">
        <a class="btn  transfer disabled">-10</a>
        <a class="btn  transfer disabled">-5</a>
        <a class="btn  transfer disabled">-1</a>
    </div>
    <div class="span1 countOnColony <?= $type . 'OnColony-' . $techId ?>" style="text-align: center">0</div>
    <div class="span2" style="text-align: center"><?= $this->translate($tech["name"]) ?></div>
    <div class="span1 countInFleet <?= $type . 'InFleet-' . $techId ?>" style="text-align: center">0</div>
    <div class="span4">
        <a class="btn  transfer disabled">+1</a>
        <a class="btn  transfer disabled">+5</a>
        <a class="btn  transfer disabled">+10</a>
    </div>
</div>
<?  endforeach; ?>