<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Trade\Module'                               => __DIR__ . '/Module.php',
    'Trade\Controller\IndexController'           => __DIR__ . '/src/Trade/Controller/IndexController.php',
    'Techtree\Controller\IndexControllerFactory' => __DIR__ . '/src/Trade/Controller/IndexControllerFactory.php',
    'Trade\Entity\Technology'                    => __DIR__ . '/src/Trade/Entity/Technology.php',
    'Trade\Entity\TechnologyFactory'             => __DIR__ . '/src/Trade/Entity/TechnologyFactory.php',
    'Trade\Table\Technology'                     => __DIR__ . '/src/Trade/Form/Technology.php',
    'Trade\Service\Gateway'                      => __DIR__ . '/src/Trade/Service/Gateway.php',
    'Trade\Service\GatewayFactory'               => __DIR__ . '/src/Trade/Service/GatewayFactory.php',
);
