<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Trade\Module'                            => __DIR__ . '/Module.php',
    'Trade\Controller\IndexController'        => __DIR__ . '/src/Trade/Controller/IndexController.php',
    'Trade\Controller\IndexControllerFactory' => __DIR__ . '/src/Trade/Controller/IndexControllerFactory.php',
    'Trade\Entity\Resource'                   => __DIR__ . '/src/Trade/Entity/Resource.php',
    'Trade\Entity\ResourceFactory'            => __DIR__ . '/src/Trade/Entity/ResourceFactory.php',
    'Trade\Entity\Technology'                 => __DIR__ . '/src/Trade/Entity/Technology.php',
    'Trade\Entity\TechnologyFactory'          => __DIR__ . '/src/Trade/Entity/TechnologyFactory.php',
    'Trade\Service\Gateway'                   => __DIR__ . '/src/Trade/Service/Gateway.php',
    'Trade\Service\GatewayFactory'            => __DIR__ . '/src/Trade/Service/GatewayFactory.php',
    'Trade\Table\Resource'                    => __DIR__ . '/src/Trade/Table/Resource.php',
    'Trade\Table\ResourceView'                => __DIR__ . '/src/Trade/Table/ResourceView.php',
    'Trade\Table\Technology'                  => __DIR__ . '/src/Trade/Table/Technology.php',
    'Trade\Table\TechnologyView'              => __DIR__ . '/src/Trade/Table/TechnologyView.php',
);
