<?php
$key = $tech['row'] . '-' . $tech['column'];
$level = isset($tech['level']) ? $tech['level'] : 0;
$class = empty($tech['level']) ? $type . ' notexists' : $type;
?>
<span class="techdata" id="techsource-<?= $key ?>">
    <a id="<?= $type ?>-<?= $tech['id'] ?>" class="btn btn-block technology <?= $class ?>" href="#techModal" data-toggle="modal">
        <?= $this->translate($tech['name']) . ' ' . $level  ?>
    </a>
    <span class="hidden data"><?= json_encode($tech) ?></span>
</span>