<?php
$key = $tech['row'] . '-' . $tech['column'];
$level = isset($tech['level']) ? $tech['level'] : 0;
$class = empty($tech['level']) ? $type . ' notexists' : $type;
?>
<span class="techdata" id="techsource-<?php echo $key ?>">
    <?php printf(
        '<a id="%s" class="%s" href="%s" data-bs-toggle="modal" data-bs-target="%s">%s</a>',
        $type.'-'.$tech['id'],
        'btn btn-block technology ' . $class,
        '/techtree/' . $type . '/' . $tech['id'],
        '#' . $type . 'Modal-' . $tech['id'],
        $this->translate($tech['name']) . ' ' . $level
    ); ?>
    <span class="d-none data"><?php echo json_encode($tech) ?></span>
</span>
