<?php

$grid_y = $tech['row'];
$grid_x = $tech['column'];
$key = $grid_y . '-' . $grid_x;

if (empty($tech['level'])):
    $class = $tech['type'] . ' notexists';
else:
    $class = $tech['type'];
endif;
?>
<span class="techdata" id="techsource-<?= $key ?>">
    <a id="tech-<?= $tech['id'] ?>" class="btn btn-block technology <?= $class ?>" href="#techModal" data-toggle="modal">
        <?= $this->translate($tech['name']) . ' ' . $tech['level']  ?>
    </a>
    <span class="hidden data"><?= json_encode($tech) ?></span>
</span>