<?php
if (!empty($poss) and $poss['level'] > 0):
    $status = $poss['status_points'];
    $width  = round(100 / ($tech['max_status_points'])); ?>
<div class="progress status_points" data-bs-toggle="tooltip" data-bs-placement="top" title="">
<?php
for ($i=1; $i<=$tech['max_status_points']; $i++):
    $n = $status-$i;
    if ($i<$status):
        if ($n<=$ap_available):
            echo '<a id="'.$type.'-'.$tech['id'].'|remove-'.$n.'" class="progress-bar bg-warning" style="width:'.$width.'%;" title="'.$i.'">'.$i.'</a>';
        else:
            echo '<span class="progress-bar bg-warning" style="width:'.$width.'%;" title="'.$i.'">'.$i.'</span>';
        endif;
    elseif ($i==$status):
        echo '<span class="progress-bar bg-warning" style="width:'.$width.'%;" title="'.$i.'">'.$i.'</span>';
    else:
        if ($i <= $status+$ap_available):
            echo '<a id="'.$type.'-'.$tech['id'].'|repair-'.($i-$status).'" class="progress-bar bg-danger" style="width:'.$width.'%;" title="'.$i.'">'.$i.'</a>';
        else:
            echo '<span class="progress-bar bg-danger" style="width:'.$width.'%;" title="'.$i.'">'.$i.'</span>';
        endif;
    endif;
endfor;
?>
</div>
<?php else : ?>
<div class="progress status_points"></div>
<?php endif; ?>
