<?php

if ($ap_spend < $tech['ap_for_levelup']):
    $width = round(100 / ($tech['ap_for_levelup']+1));
else:
    $width = round(100 / $tech['ap_for_levelup']);
endif;
?>
<div class="progress ap_spend" rel="tooltip" data-placement="top" data-original-title="eingesetzt: <?php echo $ap_spend ?>|benötigt:<?php echo $tech['ap_for_levelup'] ?>">
    <?php for ($i = 1; $i <= $ap_spend; $i++):
        echo '<span class="progress-bar progress-bar-success" style="width:'.$width.'%;">'.$i.'</span>';
    endfor;
    for ($j = $i; $j <= ($tech['ap_for_levelup']); $j++):
        if (($j-$i+1) <= $ap_available):
            echo '<a id="'.$type.'-'.$tech['id'].'|add-'.($j-$i+1).'" class="progress-bar progress-bar--info" style="width:'.$width.'%;">'.$j.'</a>';
        else:
            echo '<span class="progress-bar progress-bar-info" style="width:'.$width.'%;">'.$j.'</span>';
        endif;
    endfor;
    if ($ap_spend < $tech['ap_for_levelup']):
    ?>
    <a id="<?php echo $type?>-<?php echo $tech['id'] ?>|add-1" class="progress-bar" style="width:<?php echo $width ?>%;"><i class="glyphicon glyphicon-plus"></i></a>
    <?php endif; ?>
</div>
