<div class="row mb-2">
    <div class="col-md-6 offset-md-3 d-flex gap-2 flex-wrap">
        <a href="#" id="toggleGridLayer" class="btn btn-secondary btn-sm">Raster an/aus</a>
        <a href="#" id="toggleSystemLayer" class="btn btn-secondary btn-sm">Planeten an/aus</a>
        <a href="#" id="toggleFleetsLayer" class="btn btn-secondary btn-sm">Flotten an/aus</a>
        <!-- <a href="#" id="toggleStationsLayer" class="btn btn-secondary btn-sm">Stationen an/aus</a> -->
    </div>
</div>
