<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Galaxy\Module'                 => __DIR__ . '/Module.php',
    'Fleets\Entity\Fleet'           => __DIR__ . '/src/Fleets/Entity/Fleet.php',
    'Fleets\Service\Gateway'        => __DIR__ . '/src/Fleets/Service/Gateway.php',
    'Fleets\Service\GatewayFactory' => __DIR__ . '/src/Fleets/Service/GatewayFactory.php',
    'Fleets\Table\Colony'           => __DIR__ . '/src/Fleets/Table/Fleet.php',
);