<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Colony\Module'                               => __DIR__ . '/Module.php',
  'ColonyTest\Service\ColonyServiceTest'        => __DIR__ . '/test/ColonyTest/Service/ColonyServiceTest.php',
  'ColonyTest\Service\ColonyServiceFactoryTest' => __DIR__ . '/test/ColonyTest/Service/ColonyServiceFactoryTest.php',
  'ColonyTest\Bootstrap'                        => __DIR__ . '/test/Bootstrap.php',
  'Colony\Service\ColonyService'                => __DIR__ . '/src/Colony/Service/ColonyService.php',
  'Colony\Service\ColonyServiceFactory'         => __DIR__ . '/src/Colony/Service/ColonyServiceFactory.php',
  'Colony\Table\ColonyTable'                    => __DIR__ . '/src/Colony/Table/ColonyTable.php',
  'Colony\Table\ColonyTableFactory'             => __DIR__ . '/src/Colony/Table/ColonyTableFactory.php',
  'Colony\Entity\ColonyFactory'                 => __DIR__ . '/src/Colony/Entity/ColonyFactory.php',
  'Colony\Entity\Colony'                        => __DIR__ . '/src/Colony/Entity/Colony.php',

  'Galaxy\Table\SystemObjectTableFactory'       => __DIR__ . '/src/Galaxy/Table/SystemObjectTableFactory',
  'Galaxy\Table\SystemObjectTable'              => __DIR__ . '/src/Galaxy/Table/SystemObjectTable'
);
