<div class="row">
    <div class="col-md-3">
      <div class="well sidebar-nav">
        <ul id="systemList" class="nav nav-list itemList">
          <li class="nav-header"><?php echo $this->translate('systems') ?></li>
        <?php foreach ($systems as $sid => $system): ?>
            <li><a href="<?php echo $this->url('galaxy/system', array('sid' => $sid)); ?>"><i class="glyphicon glyphicon-globe"></i> <?php echo $system['name'] ?></a></li>
        <?php endforeach; ?>
        </ul>
      </div><!--/.well -->
    </div><!--/span-->
    <div id="parallax" class="parallax-viewport span6">
        <div id="background1" class="parallax-layer">
        </div>
        <div id="systemFrame" class="parallax-layer">
        </div>
        <div id="background2" class="parallax-layer">
        <?php foreach ($systems as $sid => $system):
            $r = round ($system['size'] / 2);
            $left = round($system['x'] * $config['scale']) + $config['offset'] - $r;
            $top  = round($system['y'] * $config['scale']) + $config['offset'] - $r;
            $imgSize = $system['size'];
        ?>
            <span class="tooltip_trigger " style="position:absolute;left:<?php echo $left ?>px;top:<?php echo $top ?>px">
        <?php  $tooltip_text = "{$system['name']} ({$system['x']}/{$system['y']}) {$this->translate($system['class'])}";
            echo '<a data-placement="bottom" rel="tooltip" href="'.$this->url('galaxy/system', array('sid' => $sid)).'" data-original-title="'.$tooltip_text.'"><img class="icon" src="/img/'.$system['icon_url'] .'" width="'.$imgSize .'" height="'.$imgSize.'" /></a>';?>
            </span>
        <?php endforeach; ?>
        </div>
    </div>
    <div class="col-md-3 well">

    </div>
</div><!--/row-->
