<div class="row-fluid">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#">Galaxy</a></li>
      <li><a href="<?= $this->url('galaxy/system', array('sid'=> null));?>">System</a></li>
    </ul>
</div>
<div class="row-fluid">
    <div class="span3">
      <div class="well sidebar-nav">
        <ul id="systemList" class="nav nav-list itemList">
          <li class="nav-header"><?= $this->translate('systems') ?></li>
        <? foreach ($systems as $sid => $system): ?>
            <li><a href="<?= $this->url('galaxy/system', array('sid' => $sid)); ?>"><i class="icon-globe"></i> <?= $system['name'] ?></a></li>
        <? endforeach; ?>
        </ul>
      </div><!--/.well -->
    </div><!--/span-->
    <div id="parallax" class="parallax-viewport span6">
        <div id="background1" class="parallax-layer">
        </div>
        <div id="systemFrame" class="parallax-layer">
        </div>
        <div id="background2" class="parallax-layer">
        <? foreach ($systems as $sid => $system):
            $r = round ($system['size'] / 2);
            $left = round($system['x'] * $config['scale']) + $config['offset'] - $r;
            $top  = round($system['y'] * $config['scale']) + $config['offset'] - $r;
            $imgSize = $system['size'];
        ?>
            <span class="tooltip_trigger " style="position:absolute;left:<?= $left ?>px;top:<?= $top ?>px">
        <?  $tooltip_text = "<b>{$system['name']}</b> ({$system['x']}/{$system['y']})<br />{$this->translate($system['class'])}";
            echo '<a data-placement="bottom" rel="tooltip" href="'.$this->url('galaxy/system', array('sid' => $sid)).'" data-original-title="'.$tooltip_text.'"><img class="icon" src="/img/'.$system['icon_url'] .'" width="'.$imgSize .'" height="'.$imgSize.'" /></a>';?>
            </span>
        <? endforeach; ?>
        </div>
    </div>
    <div class="span3 well">

    </div>
</div><!--/row-->
