<div class="row-fluid">
<div class="span3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
      <li class="nav-header">Eigene Flotten</li>
      <li class="active"><a href="#"><i class="icon-plane icon-white"></i> Link</a></li>
      <li><a href="#"><i class="icon-plane"></i> Link</a></li>
      <li><a href="#"><i class="icon-plane"></i> Link</a></li>
      <li><a href="#"><i class="icon-plane"></i> Link</a></li>
      <li class="nav-header">Fremde Flotten</li>
      <li><a href="#"><i class="icon-plane"></i> Link</a></li>
      <li><a href="#"><i class="icon-plane"></i> Link</a></li>
      <li><a href="#"><i class="icon-plane"></i> Link</a></li>
      <li><a href="#"><i class="icon-plane"></i> Link</a></li>
      <li><a href="#"><i class="icon-plane"></i> Link</a></li>
      <li><a href="#"><i class="icon-plane"></i> Link</a></li>
      <li class="nav-header">Stationen</li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li class="nav-header">Planeten/Monde</li>
      <li><a href="#"><i class="icon-globe"></i> Link</a></li>
      <li><a href="#"><i class="icon-globe"></i> Link</a></li>
      <li><a href="#"><i class="icon-globe"></i> Link</a></li>
      <li class="nav-header">Sonstige Objekte</li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
      <li><a href="#">Link</a></li>
    </ul>
  </div><!--/.well -->
</div><!--/span-->
<div class="parallax-viewport span6">
  <div id="layerA" class="parallax-layer">
    redredredredredredredredredred
  </div>
  <div id="layerB" class="parallax-layer">
    blue blueblueblueblueblueblueblue
  </div>
  <div id="layerC" class="parallax-layer">
  </div>
</div>
<div class="span3 well">
  <p>
    Koordinaten: <br/>
    [123;456;1]<br />
    Info:<br />
    abxbcbdafgagds safds fd<br/>
    dsfghfdgh sfgsfd gfdg <br />
  </p>
  <hr />
  <div class="row-fluid">
    <div class="span6"><a href="#" class="btn btn-large btn-block">test</a></div>
    <div class="span6"><a href="#" class="btn btn-large btn-block">test</a></div>
  </div>
  <div class="row-fluid">
    <div class="span6"><a href="#" class="btn btn-large btn-block">test</a></div>
    <div class="span6"><a href="#" class="btn btn-large btn-block">test</a></div>
  </div>
  <div class="row-fluid">
    <div class="span6"><a href="#" class="btn btn-large btn-block">test</a></div>
    <div class="span6"><a href="#" class="btn btn-large btn-block">test</a></div>
  </div>

</div>
</div><!--/row-->
