<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Resources\Module'                          => __DIR__ . '/Module.php',
    'Resources\Controller\JsonController'       => __DIR__ . '/src/Resources/Controller/JsonController.php',
    'Techtree\Controller\JsonControllerFactory' => __DIR__ . '/src/Resources/Controller/JsonControllerFactory.php',
    'Resources\Controller\Plugin\Resources'     => __DIR__ . '/src/Resources/Controller/Plugin/Resources.php',
    'Resources\Entity\Colony'                   => __DIR__ . '/src/Resources/Entity/Colony.php',
    'Resources\Entity\ColonyFactory'            => __DIR__ . '/src/Resources/Entity/ColonyFactory.php',
    'Resources\Entity\Resource'                 => __DIR__ . '/src/Resources/Entity/Resource.php',
    'Resources\Entity\ResourceFactory'          => __DIR__ . '/src/Resources/Entity/UserFactory.php',
    'Resources\Entity\User'                     => __DIR__ . '/src/Resources/Entity/User.php',
    'Resources\Service\Exception'               => __DIR__ . '/src/Resources/Service/Exception.php',
    'Resources\Service\Gateway'                 => __DIR__ . '/src/Resources/Service/Gateway.php',
    'Resources\Service\GatewayFactory'          => __DIR__ . '/src/Resources/Service/GatewayFactory.php',
    'Resources\Table\Colony'                    => __DIR__ . '/src/Resources/Table/Colony.php',
    'Resources\Table\Resource'                  => __DIR__ . '/src/Resources/Table/Resource.php',
    'Resources\Table\User'                      => __DIR__ . '/src/Resources/Table/User.php',
    'Resources\View\Helper\Resources'           => __DIR__ . '/src/Resources/View/Helper/Resources.php',
);
