<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Resources\Module'                 => __DIR__ . '/Module.php',
    'Resources\Mapper\Colony'          => __DIR__ . '/src/Resources/Mapper/Colony.php',
    'Resources\Mapper\ColonyFactory'   => __DIR__ . '/src/Resources/Mapper/ColonyFactory.php',
    'Resources\Mapper\Resource'        => __DIR__ . '/src/Resources/Mapper/Resource.php',
    'Resources\Mapper\ResourceFactory' => __DIR__ . '/src/Resources/Mapper/UserFactory.php',
    'Resources\Mapper\User'            => __DIR__ . '/src/Resources/Mapper/User.php',
    'Resources\Service\Exception'      => __DIR__ . '/src/Resources/Service/Exception.php',
    'Resources\Service\Gateway'        => __DIR__ . '/src/Resources/Service/Gateway.php',
    'Resources\Service\GatewayFactory' => __DIR__ . '/src/Resources/Service/GatewayFactory.php',
    'Resources\Table\Colony'           => __DIR__ . '/src/Resources/Table/Colony.php',
    'Resources\Table\Resource'         => __DIR__ . '/src/Resources/Table/Resource.php',
    'Resources\Table\User'             => __DIR__ . '/src/Resources/Table/User.php',
);